asterisk:
  image: safchain/asterisk-consul-amqp
  links:
    - consul
    - rabbitmq
api-gateway:
  image: quintana/api_gateway
  links:
    - consul
  ports:
    - "8888:80"
  expose:
    - 80/tcp
consul:
  image: consul
  ports:
    - "8500:8500"
kamailio:
  image: quintana/kamailio-consul-template
  links:
    - consul
    - asterisk
  ports:
    - "5060:5060/udp"
  expose:
    - 5060/udp
rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
  expose:
    - 5672/tcp
    - 15672/tcp
